language: node_js
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_f0cc5a0bf9b1_key -iv $encrypted_f0cc5a0bf9b1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- yarn lint
- yarn test
- NODE_ENV=$([ "$TRAVIS_BRANCH" == "master" ] && echo "production" || echo "staging")
  yarn build
deploy:
- provider: gae
  skip_cleanup: true
  keyfile: service-account-staging.json
  project: unpkg-staging
  config: app-staging.yaml
  on:
    branch: staging
- provider: gae
  skip_cleanup: true
  keyfile: service-account.json
  project: unpkg-gcp
  config: app.yaml
  on:
    branch: master
